import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setform] = useState({
    name: "",
    prompt: "",
    photo: "",
  });

  const [generatingImg, setgeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1
          className="font-extrabold
         text-[#222328] text-[32px]"
        >
          Create
        </h1>
        <p
          className="mt-2 text-[#666e75]
         text-[16px] max-w-[500px]"
        >
          Create images generated by DALL-E AI
        </p>
      </div>

      <form className="mt-16"></form>
    </section>
  );
};

export default CreatePost;
